# Source: https://www.jverdeyen.be/docker/how-php-symfony-coreos-docker/

app:
    image: yappabe/data
    volumes:
        - .:/var/www/app
        - /vendor
    tty: true

nginx:
    image: yappabe/nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    environment:
        DOCUMENT_ROOT: /var/www/app/web
        INDEX_FILE: app_dev.php
        PHP_FPM_SOCKET: php:9000

php:
    image: yappabe/php
    expose:
        - 9000
    volumes_from:
        - app
